const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SET_USER_ROLE: 'SET_USER_ROLE',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_NEW_POST: "GET_NEW_POST",

    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    // USER
    GET_CURRENT: 'GET_CURRENT',
    GET_TOTAL_POSTS_SAVED: 'GET_TOTAL_POSTS_SAVED',
    SET_USER_INFO: 'SET_USER_INFO',

    FETCH_SAVED_POSTS_SUCCESS: 'FETCH_SAVED_POSTS_SUCCESS',
    FETCH_SAVED_POSTS_FAILURE: 'FETCH_SAVED_POSTS_FAILURE',
    DELETE_SAVED_POST_SUCCESS: 'DELETE_SAVED_POST_SUCCESS',
    DELETE_SAVED_POST_FAILURE: 'DELETE_SAVED_POST_FAILURE',

    //ADMIN
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

    FETCH_TYPE_POSTS_REQUEST: 'FETCH_TYPE_POSTS_REQUEST',
    FETCH_TYPE_POSTS_SUCCESS: 'FETCH_TYPE_POSTS_SUCCESS',
    FETCH_TYPE_POSTS_FAILURE: 'FETCH_TYPE_POSTS_FAILURE',

    CREATE_TYPE_POST_REQUEST: 'CREATE_TYPE_POST_REQUEST',
    CREATE_TYPE_POST_SUCCESS: 'CREATE_TYPE_POST_SUCCESS',
    CREATE_TYPE_POST_FAILURE: 'CREATE_TYPE_POST_FAILURE',

    UPDATE_TYPE_POST_REQUEST: 'UPDATE_TYPE_POST_REQUEST',
    UPDATE_TYPE_POST_SUCCESS: 'UPDATE_TYPE_POST_SUCCESS',
    UPDATE_TYPE_POST_FAILURE: 'UPDATE_TYPE_POST_FAILURE',

    DELETE_TYPE_POST_REQUEST: 'DELETE_TYPE_POST_REQUEST',
    DELETE_TYPE_POST_SUCCESS: 'DELETE_TYPE_POST_SUCCESS',
    DELETE_TYPE_POST_FAILURE: 'DELETE_TYPE_POST_FAILURE',


    FETCH_UPGRADE_REQUESTS_SUCCESS: 'FETCH_UPGRADE_REQUESTS_SUCCESS',
    FETCH_UPGRADE_REQUESTS_FAILURE: 'FETCH_UPGRADE_REQUESTS_FAILURE',
}

export default actionTypes